---
- hosts: docker
  become: true
  tasks:
  - name: Copy apache scripts
    ansible.builtin.copy:
      src: '{{ item }}'
      dest: '/usr/local/bin/'
      mode: '755'
    loop:
      - './remote_scripts/restart-gub-apache.sh'
      - './remote_scripts/reload-gub-apache.sh'
      - './remote_scripts/test-gub-apache.sh'
  - name: Copy certificates
    ansible.builtin.copy:
      src: '{{ item }}'
      dest: '/opt/gub-apache2/ssl/certs/'
      mode: '600'
      owner: 'root'
    notify: reload apache
    loop:
      - './ssl/certs/ub-gu-se.pem'
      - './ssl/certs/interm_geant.pem'
  - name: Copy private key
    ansible.builtin.copy:
      src: './ssl/private/ub-gu-se.key'
      dest: '/opt/gub-apache2/ssl/private/'
      mode: '600'
      owner: root
    notify: reload apache
  handlers:
    - name: reload apache
      ansible.builtin.shell:
        cmd: 'reload-gub-apache.sh'
- hosts: apache
  become: true
  tasks:
  - name: Copy certificates
    ansible.builtin.copy:
      src: '{{ item }}'
      dest: '/etc/ssl/certs/'
      mode: '600'
      owner: 'root'
    notify: reload apache
    loop:
      - './ssl/certs/ub-gu-se.pem'
      - './ssl/certs/interm_geant.pem'
  - name: Copy private key
    ansible.builtin.copy:
      src: './ssl/private/ub-gu-se.key'
      dest: '/etc/ssl/private/'
      mode: '600'
      owner: root
    notify: reload apache
  handlers:
    - name: reload apache
      ansible.builtin.service:
        name: apache2
        state: reloaded
...
