FROM debian:bookworm

# Install ansible 
RUN apt-get update && \
    apt-get install -y software-properties-common python3-launchpadlib && \
    apt-add-repository --yes --update ppa:ansible/ansible && \
    apt-get install -y ansible && \
    apt-get clean

# Set working directory
WORKDIR /ansible
COPY . /ansible

COPY ./docker/docker-entrypoint.sh /usr/local/bin/

# Set entrypoint and default command
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["--help"}
